# Generated by Django 5.2.6 on 2025-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('ADU', 'Attestation de Droit d’Usage (ADU)'), ('ATTRIBUTION', 'Lettre d’attribution'), ('VILLAGEOISE', 'Attestation villageoise')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents_verification/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
