# Generated by Django 5.2.6 on 2025-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='email',
            field=models.EmailField(default='non precisé', max_length=254),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='telephone',
            field=models.CharField(default='Non précisé', max_length=20),
        ),
    ]
