# Generated by Django 5.2.6 on 2025-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_documentverification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverification',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
