# Generated by Django 5.2.7 on 2025-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='terrains/')),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
