# Generated by Django 5.2.6 on 2025-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeSuivie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_dossier', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
