# Generated by Django 5.2.6 on 2025-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesuivie',
            name='telephone',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
    ]
